admin_user_language.settings:
  type: config_object
  mapping:
    default_language_to_assign:
      type: string
      label: 'The default langcode to assign'
    prevent_user_override:
      type: boolean
      label: 'A boolean to force the admin language on every user save'